/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SixElements } from "./SixElements";

export { SixElements__factory } from "./factories/SixElements__factory";
